### ISSUE TITLE
Adding Feedback Page

### ISSUE THREAD

**Issue by sharur7** [smaranjitghose/auto_vaidya#18]
### Adding Feedback Page

As we know that feedback plays a very good role in knowing any loopholes or how can we improve our work.
I want to take up this issue by creating a feedback page for our project.
@smaranjitghose I want to work on this.

**Comment by abhu-A-J** [comment]
> ### Adding Feedback Page
> As we know that feedback plays a very good role in knowing any loopholes or how can we improve our work.
> I want to take up this issue by creating a feedback page for our project.
> @smaranjitghose I want to work on this.

Can you explain what all you will be doing here! Seems good to me but let me know the process!!

**Comment by sharur7** [comment]
It would be like a feedback form. But here, the user will be able to give feedback through rating from 1 to 5. Also, the text box will be added to know some more feedback, email and name will be taken as inputs to know who has given the feedback.

**Comment by abhu-A-J** [comment]
> It would be like a feedback form. But here, the user will be able to give feedback through rating from 1 to 5. Also, the text box will be added to know some more feedback, email and name will be taken as inputs to know who has given the feedback.

Sounds good go ahead!!

**Comment by smaranjitghose** [comment]
> It would be like a feedback form. But here, the user will be able to give feedback through rating from 1 to 5. Also, the text box will be added to know some more feedback, email and name will be taken as inputs to know who has given the feedback.

One suggestion. The rating of the project is definitely good to have but our primary users are doctors or medical practitioners here so I would suggest having the following parameters in addition to the overall rating:
- Name
- __Designation__
- Did you find our methods appropriate to diagnose the problem you were interested in?
- Do you think we are missing out on something?
- What is your take on the importance of the problem we are solving? How much useful is our tool?
- Would you like to work with us closely for some other problem?

**Comment by sharur7** [comment]
Yes, Sure! that would be more informative and good!
