### ISSUE TITLE
Adding a loader screen!

### ISSUE THREAD

**Issue by sameersrivastava13** [smaranjitghose/auto_vaidya#19]
To give an end user immediate feedback that an application is starting and loading in the background.

Here is an example that i have implemented.

![splash](https://user-images.githubusercontent.com/56088741/90332256-fab02800-dfd8-11ea-94be-7e689777b93a.gif)

**Comment by abhu-A-J** [comment]
> an example that i have implemented

I would prefer a much simpler version of the loader you are showing here! You can take inspiration from loaders like:
https://mhnpd.github.io/react-loader-spinner/

I would suggest go for the circular once and make it a dark blue color. Also try writing it from scratch!

**Comment by sameersrivastava13** [comment]
@abhu-A-J for adding this splash screen i have used much simpler version only by adding just few lines of code.
