### ISSUE TITLE
Change Font Family and Improve Navbar

### ISSUE THREAD

**Issue by abhu-A-J** [smaranjitghose/auto_vaidya#22]
Currently, the font-families used aren't so exciting for the project.  Use the appropriate combination to add some more flare to the project.

You can use tools like : 
1. https://fontpair.co/
2. https://fonts.google.com/

After that design a new Navbar for the application, which satisfy the following requirements:
1. The navbar must need to have a white background and a box-shadow on the bottom and must stick to the top at all times.
2. Use appropriate colors (new-pallet) and set-up as CSS-Variables for people to use again.
3. The nav links on hover need to change color and add a small underline effect.
4. The navbar must be fully responsive on all screens.

**Comment by sameersrivastava13** [comment]
@abhu-A-J i would like to take the issue for changing the font-families.
Can you assign that to me? Or do i have to take the entire issue.

**Comment by abhu-A-J** [comment]
> @abhu-A-J i would like to take the issue for changing the font-families.
> Can you assign that to me? Or do i have to take the entire issue.

Complete you previous issues first ! Then you may take it!
