### ISSUE TITLE
Add the pricing page

### ISSUE THREAD

**Issue by dipanshparmar** [smaranjitghose/auto_vaidya#38]
Hello there,
As I can see that there is a requirement for the Pricing page but no one has actually worked on the page.
![image](https://user-images.githubusercontent.com/49204837/91634211-48328900-ea0c-11ea-900d-f2963a38622f.png)
So, I would love to work on page design and development. :)

**Comment by dipanshparmar** [comment]
@smaranjitghose please assign me this task if there is a requirement.

**Comment by anushbhatia** [comment]
comment on that page will assign you this issue

**Comment by dipanshparmar** [comment]
Comment on which page?

**Comment by anushbhatia** [comment]
#44

**Comment by dipanshparmar** [comment]
Done!
