### ISSUE TITLE
Pricing Page

### ISSUE THREAD

**Issue by anushbhatia** [smaranjitghose/auto_vaidya#44]

**Comment by dipanshparmar** [comment]
@anushbhatia  I would love to work on this issue. Please assign me this issue.

**Comment by dipanshparmar** [comment]
@anushbhatia Can I have the product details and the pricing details, please.

**Comment by smaranjitghose** [comment]
> @anushbhatia Can you please provide me the product details and pricing details on [LinkedIn](https://www.linkedin.com/in/dipansh-parmar-346774181/), or should I add dummy text for now?

Add Dummy values for now. For reference have a look at any small scale AI startup's pricing if you wish
