### ISSUE TITLE
Skin Cancer Detection

### ISSUE THREAD

**Issue by SoniGarima** [smaranjitghose/auto_vaidya#51]
Could we add a Skin Cancer Detector as well to the project ?
We can use [skin-cancer-mnist-ham10000](https://www.kaggle.com/kmader/skin-cancer-mnist-ham10000) dataset.

**Comment by smaranjitghose** [comment]
> Could we add a Skin Cancer Detector as well to the project ?
> We can use [skin-cancer-mnist-ham10000](https://www.kaggle.com/kmader/skin-cancer-mnist-ham10000) dataset.

Sure!

**Comment by SoniGarima** [comment]
Sir, there is no branch named 'test', so which branch the PR should be for?

**Comment by smaranjitghose** [comment]
> Sir, there is no branch named 'test', so which branch the PR should be for?

Can you check once more please

**Comment by SoniGarima** [comment]
Yes sir, it is there now. As you have already merged the PR, should I start working on the streamlit app?

**Comment by smaranjitghose** [comment]
> Yes sir, it is there now. As you have already merged the PR, should I start working on the streamlit app?

Sure. Have a look at the [ReadME](https://github.com/smaranjitghose/img_ai_app_boilerplate) of this repo if you need some pointers on how to get started.

The default app is already present on the ```master``` as well as ```test``` branch

For this task, define a ```skin_cancer_mnist.py``` for the prediction function. and import it inside ```app.py``` and create a Skin Cancer page for it, where if one uploads an image, the inference is provided. 

I would appreciate the addition of some background info regarding the problem in hand to be added to the page as well😊

**Comment by SoniGarima** [comment]
Sure, will start working on it. Thanks!
