### ISSUE TITLE
Default Streamlit App

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/auto_vaidya#60]

**Comment by smaranjitghose** [comment]
> _No description provided._

For the ```test``` delete all other files except the ReadME and set up a default streamlit app using this [repo](https://github.com/smaranjitghose/img_ai_app_boilerplate)

**Comment by Preetesh21** [comment]
So in total, there will be only two files?Readme and app.py.

**Comment by smaranjitghose** [comment]
> So in total, there will be only two files?Readme and app.py.

For the ```test``` branch we need the following:
- app.py
- README.MD
- LICENSE
- setup.sh
- requirements.txt
- Procfile
-.gitignorefile

Please have a look at the repo I gave for reference. I have laid out most of the work there

**Comment by Preetesh21** [comment]
yes sir

**Comment by Preetesh21** [comment]
Sir, I have given a very basic structure for the app. If you could kindly verify.

**Comment by smaranjitghose** [comment]
> Sir, I have given a very basic structure for the app. If you could kindly verify.

BTW @Preetesh21 Are you a part of HackInCodes CH-20?

**Comment by Preetesh21** [comment]
No sir I am not part of HackInCodes. I have applied for SLoP.
