### ISSUE TITLE
Issue and Pr_templates

### ISSUE THREAD

**Issue by ritiksoni00** [smaranjitghose/auto_vaidya#7]
Can i work on this so that contributors have clarification for Make pr and Issues..?

**Comment by abhu-A-J** [comment]
@ritiksoni00 Any updates??

**Comment by ritiksoni00** [comment]
yeah! just making it! sorry for late but her i already made a pr for that @sameersrivastava13  closed that!!

**Comment by ritiksoni00** [comment]
@abhu-A-J  can you please look at the closed Pr for this issue

**Comment by abhu-A-J** [comment]
> @abhu-A-J can you please look at the closed Pr for this issue

Sure Let me have a look!!!

**Comment by smaranjitghose** [comment]
As I mentioned earlier, for HackinCodes we cannot grant this a valid contribution for the project. You are expected to contribute to the codebase itself. And please do not raise issues without consulting with the mentors
